panda_arm:

  panda_joint1_joint_limits:
    lower: -2.8973
    upper: 2.8973
  panda_joint2_joint_limits:
    lower: -1.7628
    upper: 1.7628
  panda_joint3_joint_limits:
    lower: -2.8973
    upper: 2.8973
  panda_joint4_joint_limits:
    lower: -3.0718
    upper: 0.0698
  panda_joint5_joint_limits:
    lower: -2.8973
    upper: 2.8973
  panda_joint6_joint_limits:
    lower: -0.0175
    upper: 3.7525
  panda_joint7_joint_limits:
    lower: -2.8973
    upper: 2.8973
  panda_finger1_joint_limits:
    lower: 0.0
    upper: 0.04
  panda_finger2_joint_limits:
    lower: 0.0
    upper: 0.04